### ISSUE TITLE
Cannot instal goldhen cheat pkg

### ISSUE THREAD

**Issue by NaisBali** [chronoss09/GoldHen-Cheats-PKG#13]
Evening bos, sory to bother

Like to ask why i cannot install pkg cheat gold hen, i means is already install but the code is not show up at my ps4. Before is no problem

Since goldhen cheat pkg 29/04/2024 until the new release 3 days ago. 

Is there somethinh wrong with the way i install it because pkg cheat from before is work fine

**Comment by chronoss09** [comment]
Delete and install a new one, it work for all without problem.

**Comment by NaisBali** [comment]
> Delete and install a new one, it work for all without problem.

You mean the pkg 21 / 05 / 2024?? 

Is it include the metal gear solid 2 and 3 cheat, i need that pkg?? 

Sorry to bother you 🙏🙏

**Comment by chronoss09** [comment]
here is the last : https://github.com/chronoss09/GoldHen-Cheats-PKG/releases/tag/v21.05.24

**Comment by NaisBali** [comment]
> here is the [last ](https://github.com/chronoss09/GoldHen-Cheats-PKG/releases/tag/v21.05.24)

Oke i will try it, hope fully there was cheat for metal gear solid 3 and 2 (cusa41303 and cusa41305) thanks bos

**Comment by NaisBali** [comment]
> here is the [last ](https://github.com/chronoss09/GoldHen-Cheats-PKG/releases/tag/v21.05.24)

Work as fine as sweet naissss, thanks from Bali 🙏🙏🙏
