### ISSUE TITLE
a few bugs...  report

### ISSUE THREAD

**Issue by remlei** [chronoss09/GoldHen-Cheats-PKG#2]
1. pressing the cancel button (circle) makes the screen all go black, you can still press the PS button and close the app and rerun the app.
2.  after installing all the cheats and prompting for shutting down the console, the ps4 just go kernel panic, the work around is as soon as you see that message, just press the PS button and close the app, and restart the console manually via power menu.

**Comment by chronoss09** [comment]
I have not this problem, the app work well for me, which firmware you have ?

**Comment by remlei** [comment]
Im on 9.00 firmware with goldhen version of the posted date of this report, sorry cant remember it anymore. 

The first one, i can easily trigger this bug in main menu of the app, since circle is the accept button in my system, I already got used to it soo much thay i always press that button as a accept button, I remember I can consistently trigger this bug in a first few runs of the app until i press cross button as a accept button specifically on this app. 

As for the 2nd one, I dont know, as soon as installation is complete prompting the system reboot or power off, the system shutoff, following with a hard drive repair after manual turn on (press twice the power button). My system dont kernel panic as long as Im not letting the app do the reboot and just do it manually.

**Comment by chronoss09** [comment]
i test all pkg cheat before posting them and all work fine...
