### ISSUE TITLE
Back 4 Blood

### ISSUE THREAD

**Issue by Blasler** [chronoss09/GoldHen-Cheats-PKG#3]
Hello I'm with 9.00 on ps4 and I installed the base PKG game without the BP patch because it's not necessary, but the game shows version 1.00 in the information when it's actually 1.08 the problem is the real trainer is for 1.08, but because the game is present as 1.00 doesn't work, but if I install the BP patch it shows in the game info 1.08 and the trainers work, but it crashes many times and the game shuts down with error on ps4

a trainer needs to be created for 1.00 (base game) to work without BP patch at 9.00

**Comment by chronoss09** [comment]
Create a fix for your game

wich cusa you have ?
