### ISSUE TITLE
Shn file

### ISSUE THREAD

**Issue by Skeptron404** [chronoss09/GoldHen-Cheats-PKG#5]
Hi chronos can u give me some shn file of this game thank you so much

Ac origins cusa05625 v1. 0
Far cry 6 cusa15778 v.1.0
Biomutant cusa09848 v1.0
Tales of arise cusa17595 v1.04
Resident evil 2 cusa09193 v1.05
The wticher 3 goty cusa05574 v1.0
Final fantasy 7 remake cusa07211 v1.0
Monster hunter world cusa07708 v1.0
Nfs heat cusa15081 v1. 07

**Comment by chronoss09** [comment]
Sorry, i have no shn file for your list, i have only this "final_fantasy_CUSA07211_01.01_aran.shn"

**Comment by Skeptron404** [comment]
Ok thank you chronos godbless
