### ISSUE TITLE
Cheat cusa10211 v1.52 bug

### ISSUE THREAD

**Issue by StandVideo** [chronoss09/GoldHen-Cheats-PKG#6]
Les cheats cusa10211 v1.52 ne fonctionne pas 
(Aucun cheat)

**Comment by chronoss09** [comment]
Vérifie la version ou le cusa de ton jeu installé.

**Comment by StandVideo** [comment]
Ces bien cusa10211 et j’ai récupérer les fichers du d’autre json du même jeu pour vérifier si un passe en le renommant est le  10237 fonctionne sur le 10211 
Mes le fichers de base cusa10211 v1.52 fonctionne pas même sur ps4traine,  il fonctionne pas en utilisant attache game 
Donc le json 10211 v1.52 a bien un problème

**Comment by chronoss09** [comment]
Essaie le dernier pkg pour voir, ça des mises à jour des json dedans...

**Comment by StandVideo** [comment]
Test ton nouveau pkg en supprimant le json avant pour être sûr que je test bien ton ficher
Cusa 10211 v1.52
Un seul cheat fonctionne dessus ces tire infinie (infinie ammor) le reste fonctionne pas
J’ai remis le ficher du cusa10213 v1.52 à la place du cusa10211 v1.52 en le renommant  en CUSA10211_01.52.json et tout fonctionne j’ai pas test pour la 1.54 vue il y a pas le ficher CUSA10211_01.54.json

**Comment by chronoss09** [comment]
Oui le CUSA10211_01.54.json n'est pas encore disponible mais j'ai mis le fixe selon ta méthode et serait-il possible que tu teste mon dernier PKG pour voir si le fixe fonctionne.

Merci !!!

**Comment by chronoss09** [comment]
Ok, je le ferais dans une prochaine version si j'oublie pas...

je passe le post en résolu et merci encore pour le beug 👍

**Comment by StandVideo** [comment]
De rien avec plaisir
